[package]
name = "async-tar"
version = "0.1.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]
tar="0.4"
futures="0.1.25"
tokio="0.1"

[dev-dependencies]
tempfile="3.0"

